name: Artifact

on: push

env:
  ARTIFACT_NAME: myartifact

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2              
        - uses: actions/upload-artifact@v6.0.0
          with:
            name: ${{env.ARTIFACT_NAME}}
            Path: .
